spring:
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: Link-Compresor
  data:
    redis:
      repositories:
        enabled: false
  boot:
    admin:
      client:
        url: http://localhost:8082
        username: test
        password: test

management:
  endpoints:
    web:
      exposure:
        include: "*"   # открыть ВСЕ actuator endpoints
  endpoint:
    health:
      show-details: ALWAYS   # показывать детали health-чеков
  health:
    diskspace:
      enabled: true
    ping:
      enabled: true

app: 
  domain: localhost:8080
  data-main: redis://172.24.121.136:6379/1
  data-alias: redis://172.24.121.136:6379/2
  https: false