spring:
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: Link-Compresor
  data:
    redis:
      repositories:
        enabled: false

app: 
  domain: localhost:8080
  data-main: redis://172.24.121.136:6379/1
  data-alias: redis://172.24.121.136:6379/2
  https: false
  