spring:
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: Link-Compresor
  data:
    redis:
      repositories:
        enabled: false
  boot:
    admin:
      client:
        url: http://localhost:8082
        username: test
        password: test

management:
  endpoints:
    web:
      exposure:
        include: "*"   # открыть ВСЕ actuator endpoints
  endpoint:
    health:
      show-details: ALWAYS   # показывать детали health-чеков
  health:
    diskspace:
      enabled: true
    ping:
      enabled: true

